# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_form.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CustomerForm(object):
    def setupUi(self, CustomerForm):
        CustomerForm.setObjectName("CustomerForm")
        CustomerForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomerForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(CustomerForm)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -570, 368, 818))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edtFullName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtFullName.setObjectName("edtFullName")
        self.verticalLayout_2.addWidget(self.edtFullName)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtShortName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtShortName.setObjectName("edtShortName")
        self.verticalLayout_2.addWidget(self.edtShortName)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edtRegistrationAddress = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtRegistrationAddress.setObjectName("edtRegistrationAddress")
        self.verticalLayout_2.addWidget(self.edtRegistrationAddress)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.edtLocationAddress = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtLocationAddress.setObjectName("edtLocationAddress")
        self.verticalLayout_2.addWidget(self.edtLocationAddress)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.edtPhone = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtPhone.setObjectName("edtPhone")
        self.verticalLayout_2.addWidget(self.edtPhone)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.edtINN = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtINN.setObjectName("edtINN")
        self.verticalLayout_2.addWidget(self.edtINN)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.edtKPP = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtKPP.setObjectName("edtKPP")
        self.verticalLayout_2.addWidget(self.edtKPP)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.edtAccount = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtAccount.setObjectName("edtAccount")
        self.verticalLayout_2.addWidget(self.edtAccount)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.edtBank = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtBank.setObjectName("edtBank")
        self.verticalLayout_2.addWidget(self.edtBank)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.edtBIK = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtBIK.setObjectName("edtBIK")
        self.verticalLayout_2.addWidget(self.edtBIK)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.edtOGRN = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtOGRN.setObjectName("edtOGRN")
        self.verticalLayout_2.addWidget(self.edtOGRN)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.edtPersonName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtPersonName.setObjectName("edtPersonName")
        self.verticalLayout_2.addWidget(self.edtPersonName)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.edtPersonPost = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtPersonPost.setObjectName("edtPersonPost")
        self.verticalLayout_2.addWidget(self.edtPersonPost)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(CustomerForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CustomerForm)
        self.buttonBox.accepted.connect(CustomerForm.accept)
        self.buttonBox.rejected.connect(CustomerForm.reject)
        QtCore.QMetaObject.connectSlotsByName(CustomerForm)

    def retranslateUi(self, CustomerForm):
        _translate = QtCore.QCoreApplication.translate
        CustomerForm.setWindowTitle(_translate("CustomerForm", "Создание заказчика"))
        self.label.setText(_translate("CustomerForm", "Полное наименование"))
        self.label_2.setText(_translate("CustomerForm", "Краткое наименование"))
        self.label_3.setText(_translate("CustomerForm", "Юридический адрес"))
        self.label_4.setText(_translate("CustomerForm", "Фактический адрес"))
        self.label_5.setText(_translate("CustomerForm", "Тел./факс"))
        self.label_6.setText(_translate("CustomerForm", "ИНН"))
        self.label_7.setText(_translate("CustomerForm", "КПП"))
        self.label_8.setText(_translate("CustomerForm", "Р/счет"))
        self.label_9.setText(_translate("CustomerForm", "Банк"))
        self.label_10.setText(_translate("CustomerForm", "БИК"))
        self.label_11.setText(_translate("CustomerForm", "ОГРН"))
        self.label_12.setText(_translate("CustomerForm", "ФИО заказчика"))
        self.label_13.setText(_translate("CustomerForm", "Должность заказчика"))

