# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.verticalWidget = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.tblApplications = QtWidgets.QTableView(self.verticalWidget)
        self.tblApplications.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblApplications.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblApplications.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblApplications.setObjectName("tblApplications")
        self.tblApplications.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tblApplications)
        self.widget_2 = QtWidgets.QWidget(self.verticalWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.btnPrintApplication = QtWidgets.QPushButton(self.widget_2)
        self.btnPrintApplication.setEnabled(False)
        self.btnPrintApplication.setObjectName("btnPrintApplication")
        self.horizontalLayout_5.addWidget(self.btnPrintApplication)
        self.btnCreateApplication = QtWidgets.QPushButton(self.widget_2)
        self.btnCreateApplication.setObjectName("btnCreateApplication")
        self.horizontalLayout_5.addWidget(self.btnCreateApplication)
        self.btnEditApplication = QtWidgets.QPushButton(self.widget_2)
        self.btnEditApplication.setEnabled(False)
        self.btnEditApplication.setObjectName("btnEditApplication")
        self.horizontalLayout_5.addWidget(self.btnEditApplication)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.verticalWidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chkNumberSearch = QtWidgets.QGroupBox(self.widget_3)
        self.chkNumberSearch.setCheckable(True)
        self.chkNumberSearch.setChecked(False)
        self.chkNumberSearch.setObjectName("chkNumberSearch")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.chkNumberSearch)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.edtNumberSearch = QtWidgets.QLineEdit(self.chkNumberSearch)
        self.edtNumberSearch.setObjectName("edtNumberSearch")
        self.verticalLayout_5.addWidget(self.edtNumberSearch)
        self.gridLayout.addWidget(self.chkNumberSearch, 0, 0, 1, 1)
        self.chkDateSearch = QtWidgets.QGroupBox(self.widget_3)
        self.chkDateSearch.setCheckable(True)
        self.chkDateSearch.setChecked(False)
        self.chkDateSearch.setObjectName("chkDateSearch")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.chkDateSearch)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.edtDateSearch = QtWidgets.QDateEdit(self.chkDateSearch)
        self.edtDateSearch.setCalendarPopup(True)
        self.edtDateSearch.setObjectName("edtDateSearch")
        self.verticalLayout_6.addWidget(self.edtDateSearch)
        self.gridLayout.addWidget(self.chkDateSearch, 0, 1, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(self.widget_3)
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout.addWidget(self.btnSearch, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.pnlDocuments = QtWidgets.QScrollArea(self.splitter)
        self.pnlDocuments.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pnlDocuments.sizePolicy().hasHeightForWidth())
        self.pnlDocuments.setSizePolicy(sizePolicy)
        self.pnlDocuments.setMinimumSize(QtCore.QSize(500, 0))
        self.pnlDocuments.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pnlDocuments.setWidgetResizable(True)
        self.pnlDocuments.setObjectName("pnlDocuments")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 575, 564))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblContractNumber = QtWidgets.QLabel(self.horizontalWidget)
        self.lblContractNumber.setObjectName("lblContractNumber")
        self.horizontalLayout.addWidget(self.lblContractNumber)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnPrintContract = QtWidgets.QPushButton(self.horizontalWidget)
        self.btnPrintContract.setEnabled(False)
        self.btnPrintContract.setObjectName("btnPrintContract")
        self.horizontalLayout.addWidget(self.btnPrintContract)
        self.btnCreateContract = QtWidgets.QPushButton(self.horizontalWidget)
        self.btnCreateContract.setObjectName("btnCreateContract")
        self.horizontalLayout.addWidget(self.btnCreateContract)
        self.btnEditContract = QtWidgets.QPushButton(self.horizontalWidget)
        self.btnEditContract.setEnabled(False)
        self.btnEditContract.setObjectName("btnEditContract")
        self.horizontalLayout.addWidget(self.btnEditContract)
        self.verticalLayout_4.addWidget(self.horizontalWidget)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblAccountNumber = QtWidgets.QLabel(self.horizontalWidget_2)
        self.lblAccountNumber.setObjectName("lblAccountNumber")
        self.horizontalLayout_2.addWidget(self.lblAccountNumber)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btnPrintAccount = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnPrintAccount.setEnabled(False)
        self.btnPrintAccount.setObjectName("btnPrintAccount")
        self.horizontalLayout_2.addWidget(self.btnPrintAccount)
        self.btnCreateAccount = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnCreateAccount.setObjectName("btnCreateAccount")
        self.horizontalLayout_2.addWidget(self.btnCreateAccount)
        self.btnEditAccount = QtWidgets.QPushButton(self.horizontalWidget_2)
        self.btnEditAccount.setEnabled(False)
        self.btnEditAccount.setObjectName("btnEditAccount")
        self.horizontalLayout_2.addWidget(self.btnEditAccount)
        self.verticalLayout_4.addWidget(self.horizontalWidget_2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalWidget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalWidget_3.setObjectName("horizontalWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblOrderNumber = QtWidgets.QLabel(self.horizontalWidget_3)
        self.lblOrderNumber.setObjectName("lblOrderNumber")
        self.horizontalLayout_3.addWidget(self.lblOrderNumber)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btnPrintOrder = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.btnPrintOrder.setEnabled(False)
        self.btnPrintOrder.setObjectName("btnPrintOrder")
        self.horizontalLayout_3.addWidget(self.btnPrintOrder)
        self.btnCreateOrder = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.btnCreateOrder.setObjectName("btnCreateOrder")
        self.horizontalLayout_3.addWidget(self.btnCreateOrder)
        self.btnEditOrder = QtWidgets.QPushButton(self.horizontalWidget_3)
        self.btnEditOrder.setEnabled(False)
        self.btnEditOrder.setObjectName("btnEditOrder")
        self.horizontalLayout_3.addWidget(self.btnEditOrder)
        self.verticalLayout_4.addWidget(self.horizontalWidget_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.pnlDocuments.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1080, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actSyncLocalStorage = QtWidgets.QAction(MainWindow)
        self.actSyncLocalStorage.setObjectName("actSyncLocalStorage")
        self.actExit = QtWidgets.QAction(MainWindow)
        self.actExit.setObjectName("actExit")
        self.actAbout = QtWidgets.QAction(MainWindow)
        self.actAbout.setObjectName("actAbout")
        self.menu.addAction(self.actAbout)
        self.menu.addAction(self.actExit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система электронной документации"))
        self.label.setText(_translate("MainWindow", "Заявки"))
        self.btnPrintApplication.setText(_translate("MainWindow", "Печать"))
        self.btnCreateApplication.setText(_translate("MainWindow", "Создать"))
        self.btnEditApplication.setText(_translate("MainWindow", "Изменить"))
        self.chkNumberSearch.setTitle(_translate("MainWindow", "Номер договора"))
        self.chkDateSearch.setTitle(_translate("MainWindow", "Дата"))
        self.btnSearch.setText(_translate("MainWindow", "Поиск"))
        self.label_2.setText(_translate("MainWindow", "Договор"))
        self.lblContractNumber.setText(_translate("MainWindow", "не создан"))
        self.btnPrintContract.setText(_translate("MainWindow", "Печать"))
        self.btnCreateContract.setText(_translate("MainWindow", "Создать"))
        self.btnEditContract.setText(_translate("MainWindow", "Изменить"))
        self.label_3.setText(_translate("MainWindow", "Счет"))
        self.lblAccountNumber.setText(_translate("MainWindow", "не создан"))
        self.btnPrintAccount.setText(_translate("MainWindow", "Печать"))
        self.btnCreateAccount.setText(_translate("MainWindow", "Создать"))
        self.btnEditAccount.setText(_translate("MainWindow", "Изменить"))
        self.label_4.setText(_translate("MainWindow", "Приказ"))
        self.lblOrderNumber.setText(_translate("MainWindow", "не создан"))
        self.btnPrintOrder.setText(_translate("MainWindow", "Печать"))
        self.btnCreateOrder.setText(_translate("MainWindow", "Создать"))
        self.btnEditOrder.setText(_translate("MainWindow", "Изменить"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.actSyncLocalStorage.setText(_translate("MainWindow", "Синхронизация локальных заявок"))
        self.actExit.setText(_translate("MainWindow", "Выход"))
        self.actAbout.setText(_translate("MainWindow", "О программе"))

