# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_form.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderForm(object):
    def setupUi(self, OrderForm):
        OrderForm.setObjectName("OrderForm")
        OrderForm.resize(400, 735)
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(OrderForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 384, 679))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edtNumber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtNumber.setObjectName("edtNumber")
        self.verticalLayout_2.addWidget(self.edtNumber)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtDate.setCalendarPopup(True)
        self.edtDate.setObjectName("edtDate")
        self.verticalLayout_2.addWidget(self.edtDate)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edtTODate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtTODate.setCalendarPopup(True)
        self.edtTODate.setObjectName("edtTODate")
        self.verticalLayout_2.addWidget(self.edtTODate)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.edtActDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtActDate.setCalendarPopup(True)
        self.edtActDate.setObjectName("edtActDate")
        self.verticalLayout_2.addWidget(self.edtActDate)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.edtController = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtController.setObjectName("edtController")
        self.verticalLayout_2.addWidget(self.edtController)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.cmbHeadSpecialist = SpecialistComboBox(self.groupBox)
        self.cmbHeadSpecialist.setObjectName("cmbHeadSpecialist")
        self.verticalLayout_3.addWidget(self.cmbHeadSpecialist)
        self.lstSpecialists = QtWidgets.QListView(self.groupBox)
        self.lstSpecialists.setObjectName("lstSpecialists")
        self.verticalLayout_3.addWidget(self.lstSpecialists)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnDeleteSpecialist = QtWidgets.QPushButton(self.widget)
        self.btnDeleteSpecialist.setEnabled(False)
        self.btnDeleteSpecialist.setObjectName("btnDeleteSpecialist")
        self.horizontalLayout.addWidget(self.btnDeleteSpecialist)
        self.btnAddSpecialist = QtWidgets.QPushButton(self.widget)
        self.btnAddSpecialist.setObjectName("btnAddSpecialist")
        self.horizontalLayout.addWidget(self.btnAddSpecialist)
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(OrderForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OrderForm)
        self.buttonBox.accepted.connect(OrderForm.accept)
        self.buttonBox.rejected.connect(OrderForm.reject)
        QtCore.QMetaObject.connectSlotsByName(OrderForm)

    def retranslateUi(self, OrderForm):
        _translate = QtCore.QCoreApplication.translate
        OrderForm.setWindowTitle(_translate("OrderForm", "Приказ"))
        self.label.setText(_translate("OrderForm", "Номер приказа"))
        self.label_2.setText(_translate("OrderForm", "Дата приказа"))
        self.label_3.setText(_translate("OrderForm", "Срок выполнения ТО"))
        self.label_4.setText(_translate("OrderForm", "Срок сдачи Акта о выполнении работ по договору"))
        self.label_5.setText(_translate("OrderForm", "Ответственный за контроль выполнения\n"
"обязательств по договору"))
        self.groupBox.setTitle(_translate("OrderForm", "Специалисты"))
        self.label_6.setText(_translate("OrderForm", "Старший группы"))
        self.btnDeleteSpecialist.setText(_translate("OrderForm", "Удалить"))
        self.btnAddSpecialist.setText(_translate("OrderForm", "Добавить"))

from models.specialist import SpecialistComboBox
