# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contract_form.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContractForm(object):
    def setupUi(self, ContractForm):
        ContractForm.setObjectName("ContractForm")
        ContractForm.resize(585, 765)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContractForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ContractForm)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 709))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edtContractNumber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtContractNumber.setObjectName("edtContractNumber")
        self.verticalLayout_2.addWidget(self.edtContractNumber)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtContractDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtContractDate.setCalendarPopup(True)
        self.edtContractDate.setObjectName("edtContractDate")
        self.verticalLayout_2.addWidget(self.edtContractDate)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edtContractFinishDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtContractFinishDate.setCalendarPopup(True)
        self.edtContractFinishDate.setObjectName("edtContractFinishDate")
        self.verticalLayout_2.addWidget(self.edtContractFinishDate)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.edtPrice = QtWidgets.QDoubleSpinBox(self.scrollAreaWidgetContents)
        self.edtPrice.setMaximum(1e+21)
        self.edtPrice.setObjectName("edtPrice")
        self.verticalLayout_2.addWidget(self.edtPrice)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.edtPaymentTerms = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.edtPaymentTerms.setObjectName("edtPaymentTerms")
        self.verticalLayout_2.addWidget(self.edtPaymentTerms)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblClient = QtWidgets.QLabel(self.widget_2)
        self.lblClient.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblClient.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblClient.setObjectName("lblClient")
        self.horizontalLayout_2.addWidget(self.lblClient)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.chkPOA = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.chkPOA.setObjectName("chkPOA")
        self.verticalLayout_2.addWidget(self.chkPOA)
        self.wdgPOA = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.wdgPOA.setObjectName("wdgPOA")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgPOA)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.wdgPOA)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.wdgPOA)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.edtPOANumber = QtWidgets.QLineEdit(self.wdgPOA)
        self.edtPOANumber.setObjectName("edtPOANumber")
        self.gridLayout.addWidget(self.edtPOANumber, 1, 0, 1, 1)
        self.edtPOADate = QtWidgets.QDateEdit(self.wdgPOA)
        self.edtPOADate.setCalendarPopup(True)
        self.edtPOADate.setObjectName("edtPOADate")
        self.gridLayout.addWidget(self.edtPOADate, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.wdgPOA)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(ContractForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ContractForm)
        self.buttonBox.accepted.connect(ContractForm.accept)
        self.buttonBox.rejected.connect(ContractForm.reject)
        self.chkPOA.toggled['bool'].connect(self.wdgPOA.setVisible)
        QtCore.QMetaObject.connectSlotsByName(ContractForm)

    def retranslateUi(self, ContractForm):
        _translate = QtCore.QCoreApplication.translate
        ContractForm.setWindowTitle(_translate("ContractForm", "Договор"))
        self.label.setText(_translate("ContractForm", "Номер договора"))
        self.label_2.setText(_translate("ContractForm", "Дата договора"))
        self.label_3.setText(_translate("ContractForm", "Дата окончания работ по договору"))
        self.label_4.setText(_translate("ContractForm", "Стоимость выполнения работ по договору"))
        self.label_5.setText(_translate("ContractForm", "Условия оплаты"))
        self.label_6.setText(_translate("ContractForm", "Организация заказчика"))
        self.lblClient.setText(_translate("ContractForm", "<не выбрано>"))
        self.chkPOA.setText(_translate("ContractForm", "По доверенности"))
        self.label_9.setText(_translate("ContractForm", "Дата доверенности"))
        self.label_10.setText(_translate("ContractForm", "№ доверенности"))

