# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contract_form.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContractForm(object):
    def setupUi(self, ContractForm):
        ContractForm.setObjectName("ContractForm")
        ContractForm.resize(412, 608)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContractForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(ContractForm)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 396, 552))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.edtContractNumber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edtContractNumber.setObjectName("edtContractNumber")
        self.verticalLayout_2.addWidget(self.edtContractNumber)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtContractDate = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.edtContractDate.setCalendarPopup(True)
        self.edtContractDate.setObjectName("edtContractDate")
        self.verticalLayout_2.addWidget(self.edtContractDate)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.cmbPaymentTerms = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.cmbPaymentTerms.setObjectName("cmbPaymentTerms")
        self.cmbPaymentTerms.addItem("")
        self.cmbPaymentTerms.addItem("")
        self.cmbPaymentTerms.addItem("")
        self.verticalLayout_2.addWidget(self.cmbPaymentTerms)
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edtPrice = QtWidgets.QDoubleSpinBox(self.widget)
        self.edtPrice.setMaximum(1e+21)
        self.edtPrice.setObjectName("edtPrice")
        self.gridLayout_3.addWidget(self.edtPrice, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.lblAdvance = QtWidgets.QLabel(self.widget)
        self.lblAdvance.setEnabled(False)
        self.lblAdvance.setObjectName("lblAdvance")
        self.gridLayout_3.addWidget(self.lblAdvance, 0, 1, 1, 1)
        self.edtAdvanceSum = QtWidgets.QDoubleSpinBox(self.widget)
        self.edtAdvanceSum.setEnabled(False)
        self.edtAdvanceSum.setMaximum(1e+21)
        self.edtAdvanceSum.setObjectName("edtAdvanceSum")
        self.gridLayout_3.addWidget(self.edtAdvanceSum, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblClient = QtWidgets.QLabel(self.widget_2)
        self.lblClient.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblClient.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblClient.setObjectName("lblClient")
        self.horizontalLayout_2.addWidget(self.lblClient)
        self.btnSelectClient = QtWidgets.QToolButton(self.widget_2)
        self.btnSelectClient.setObjectName("btnSelectClient")
        self.horizontalLayout_2.addWidget(self.btnSelectClient)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.chkPOAClient = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.chkPOAClient.setCheckable(True)
        self.chkPOAClient.setChecked(False)
        self.chkPOAClient.setObjectName("chkPOAClient")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.chkPOAClient)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.chkPOAClient)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.edtPOAClientDate = QtWidgets.QDateEdit(self.chkPOAClient)
        self.edtPOAClientDate.setCalendarPopup(True)
        self.edtPOAClientDate.setObjectName("edtPOAClientDate")
        self.gridLayout_2.addWidget(self.edtPOAClientDate, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.chkPOAClient)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.edtPOAClientNumber = QtWidgets.QLineEdit(self.chkPOAClient)
        self.edtPOAClientNumber.setObjectName("edtPOAClientNumber")
        self.gridLayout_2.addWidget(self.edtPOAClientNumber, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.chkPOAClient)
        self.chkPOAContractor = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.chkPOAContractor.setCheckable(True)
        self.chkPOAContractor.setChecked(False)
        self.chkPOAContractor.setObjectName("chkPOAContractor")
        self.gridLayout = QtWidgets.QGridLayout(self.chkPOAContractor)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.chkPOAContractor)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.chkPOAContractor)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.edtPOAContractorNumber = QtWidgets.QLineEdit(self.chkPOAContractor)
        self.edtPOAContractorNumber.setObjectName("edtPOAContractorNumber")
        self.gridLayout.addWidget(self.edtPOAContractorNumber, 1, 0, 1, 1)
        self.edtPOAContractorDate = QtWidgets.QDateEdit(self.chkPOAContractor)
        self.edtPOAContractorDate.setCalendarPopup(True)
        self.edtPOAContractorDate.setObjectName("edtPOAContractorDate")
        self.gridLayout.addWidget(self.edtPOAContractorDate, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.chkPOAContractor)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.buttonBox = QtWidgets.QDialogButtonBox(ContractForm)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ContractForm)
        self.buttonBox.accepted.connect(ContractForm.accept)
        self.buttonBox.rejected.connect(ContractForm.reject)
        QtCore.QMetaObject.connectSlotsByName(ContractForm)

    def retranslateUi(self, ContractForm):
        _translate = QtCore.QCoreApplication.translate
        ContractForm.setWindowTitle(_translate("ContractForm", "Договор"))
        self.label.setText(_translate("ContractForm", "Номер договора"))
        self.label_2.setText(_translate("ContractForm", "Дата договора"))
        self.label_5.setText(_translate("ContractForm", "Условия оплаты"))
        self.cmbPaymentTerms.setItemText(0, _translate("ContractForm", "Предоплата"))
        self.cmbPaymentTerms.setItemText(1, _translate("ContractForm", "Постоплата"))
        self.cmbPaymentTerms.setItemText(2, _translate("ContractForm", "Авансовый платеж"))
        self.label_4.setText(_translate("ContractForm", "Общая стоимость"))
        self.lblAdvance.setText(_translate("ContractForm", "Сумма аванса"))
        self.label_6.setText(_translate("ContractForm", "Организация заказчика"))
        self.lblClient.setText(_translate("ContractForm", "<не выбрано>"))
        self.btnSelectClient.setText(_translate("ContractForm", "..."))
        self.chkPOAClient.setTitle(_translate("ContractForm", "По доверенности (заказчик)"))
        self.label_9.setText(_translate("ContractForm", "Дата доверенности"))
        self.label_10.setText(_translate("ContractForm", "№ доверенности"))
        self.chkPOAContractor.setTitle(_translate("ContractForm", "По доверенности (исполнитель)"))
        self.label_11.setText(_translate("ContractForm", "№ доверенности"))
        self.label_12.setText(_translate("ContractForm", "Дата доверенности"))

